### ISSUE TITLE
Place for sharing and discussing this project.

### ISSUE THREAD

**Issue by Skrys33** [Dofus-Batteries-Included/DBI#51]
Hello,

Is there a place where we could discuss this project?
I'm thinking, for example, of a Discord related to the project or a dedicated post on a server like Cadernis?

**Comment by ismailbennani** [comment]
Hi, there is a discord server: https://discord.gg/sNEtjhVMzQ
However the project has been stopped when ankama said users of Melon Loader would be automatically banned. I don't want to play cat and mouse with them.
